import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { alertVariants } from './components/alert/alert.styles';
import { cardVariants } from './components/card/card.styles';
import { toastVariants } from './components/toast/toast.styles';
import { flexVariants } from './components/flex/flex.styles';
import {
  selectTriggerVariants,
  selectContentVariants,
  selectItemVariants,
} from './components/select/select.styles';
import { buttonVariants } from './components/button/button.styles';

/**
 * **Feature: code-review-engine, Property 3: Token Usage Consistency**
 * **Validates: Requirements 3.2**
 *
 * For any component variant class generated by CVA, the class string
 * SHALL NOT contain hardcoded color values (like `bg-white`) but
 * SHALL use design token classes (like `bg-neutral-50`).
 */
describe('Token Usage Consistency', () => {
  // Only check for hardcoded background colors
  // text-white/text-black are acceptable for contrast on colored backgrounds
  const HARDCODED_BG_COLORS = ['bg-white', 'bg-black'];

  const checkNoHardcodedColors = (classes: string) => {
    for (const hardcoded of HARDCODED_BG_COLORS) {
      expect(classes).not.toContain(hardcoded);
    }
  };

  describe('Alert Variants', () => {
    it('should not use hardcoded colors', () => {
      const statuses = ['info', 'success', 'warning', 'error'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...statuses), (status) => {
          const classes = alertVariants({ status });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Card Variants', () => {
    it('should not use hardcoded colors', () => {
      const variants = ['elevated', 'outlined', 'filled'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...variants), (variant) => {
          const classes = cardVariants({ variant });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Toast Variants', () => {
    it('should not use hardcoded colors', () => {
      const statuses = ['default', 'success', 'warning', 'error'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...statuses), (status) => {
          const classes = toastVariants({ status });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Flex Variants', () => {
    it('should not use hardcoded colors', () => {
      const directions = ['row', 'row-reverse', 'column', 'column-reverse'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...directions), (direction) => {
          const classes = flexVariants({ direction });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Select Variants', () => {
    it('should not use hardcoded colors in trigger', () => {
      const variants = ['default', 'error'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...variants), (variant) => {
          const classes = selectTriggerVariants({ variant });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });

    it('should not use hardcoded colors in content', () => {
      const classes = selectContentVariants();
      checkNoHardcodedColors(classes);
    });

    it('should not use hardcoded colors in item', () => {
      const classes = selectItemVariants();
      checkNoHardcodedColors(classes);
    });
  });

  describe('Button Variants', () => {
    it('should not use hardcoded colors', () => {
      const variants = ['primary', 'secondary', 'outline', 'ghost', 'destructive'] as const;

      fc.assert(
        fc.property(fc.constantFrom(...variants), (variant) => {
          const classes = buttonVariants({ variant });
          checkNoHardcodedColors(classes);
        }),
        { numRuns: 100 }
      );
    });
  });
});
